@startuml
'https://plantuml.com/class-diagram



class App {
+ main()
+ start()
}

class Lists{
-lists[] : ArrayList<ToDoList>
addList()
removeList()
}

class ToDoList {
- toDoTitle : String
- items[] : ArrayList<Item>
setTitle()
addItem()
removeItem()
displayItems()
}

class Item {
itemStatus : boolean
itemDescription : String
itemDueDate : String

editDescription()
editStatus()
editDueDate()
}

javafx.Application <|- App
App *-- Lists
Lists <-- ToDoList
ToDoList o-- Item

@enduml